# Generated by Django 5.2 on 2026-08-31 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_types",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "audio"), (2, "video"), (3, "pdf")],
                default=2,
                verbose_name="file type",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="products.product",
                verbose_name="product",
            ),
        ),
    ]
