# Generated by Django 5.2 on 2026-08-31 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_file_file_types_alter_file_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="file_types",
            new_name="file_type",
        ),
    ]
